name: "Yarn Install"
description: "Install deps with yarn"
runs:
  using: "composite"    
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install --prefer-offline --frozen-lockfile
      shell: bash
      working-directory: ${{ inputs.working-dir }}
    - uses: vtno/seei/.github/actions/yarn-cache@main
