name: "Build, Test and Lint"

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string

concurrency:
  group: ${GITHUB_REF#refs/heads/}
  cancel-in-progress: true

jobs:
  install:
    name: "Install deps"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        working-directory: ${{ inputs.working-dir }}
      - uses: vtno/seei/.github/actions/yarn-cache@main

  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
      - uses: vtno/seei/.github/actions/yarn-build@main

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vtno/seei/.github/actions/yarn-cache@main
      - name: Install Dependencies From Cache
        run: yarn install -offline --frozen-lockfile
      - name: Unit Test
        run: yarn test
        working-directory: ${{ inputs.working-dir }}

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vtno/seei/.github/actions/yarn-cache@main
      - name: Install Dependencies From Cache
        run: yarn install -offline --frozen-lockfile
      - name: Unit Test
        run: yarn lint
        working-directory: ${{ inputs.working-dir }}
